### PR TITLE
Fix(User): User Service

### LINKED ISSUE #5: Domain services
Refactor controllers to put all queries in single location to improve usability and maintainability.

### PR DESCRIPTION
**Pull request by iroegbu**
Includes services for user domain to make methods more reusable and maintainable.

closes #5

### CODE REVIEW

File: user/user.controller.js [hunk 1]
```diff
@@ -1,29 +1,47 @@
...
-    }
-    catch (err) {
-        console.log(err.message)
+    //TODO: Use joi to achieve this
+    if (requestBody.password !== req.body.confirmPassword) {
+      return res.status(400).send({ detail: 'Password Mismatch' });
     }
-}
 
+    //TODO: this doesn't belong in controller
```
Comment (Damephena) [inline user/user.controller.js:35]: Hei Jesu. *Insert The Simson's mom hiding face sticker

File: user/user.service.js [hunk 2]
```diff
@@ -0,0 +1,49 @@
+const { User, validate } = require('./user.model');
```
Comment (Damephena) [inline user/user.service.js:1]: God when😪🤲🏽 @iroegbu

**Review by Damephena — APPROVED** [review]
Thank you. Would implement and revert.
